# Generated by Django 4.2.5 on 2023-09-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_student_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
