# Generated by Django 4.2.5 on 2023-09-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_student_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="fee",
            new_name="paid_fees",
        ),
    ]
