# Generated by Django 4.2.5 on 2023-09-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_fee_student_paid_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="paid_fees",
            field=models.IntegerField(default=15000, verbose_name="School fees"),
        ),
    ]
