# Generated by Django 4.2.5 on 2023-09-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_bookinstance_imprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.genre",
            ),
        ),
    ]
