# Generated by Django 4.2.5 on 2023-09-13 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0004_alter_book_genre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={"ordering": ["book"]},
        ),
        migrations.RemoveField(
            model_name="bookinstance",
            name="due_back",
        ),
        migrations.RemoveField(
            model_name="bookinstance",
            name="imprint",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.AddField(
            model_name="bookinstance",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="due_back",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("o", "On loan"), ("a", "Available")],
                default="a",
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
