# Generated by Django 4.2.5 on 2023-09-13 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_bookinstance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
