# Generated by Django 4.2.5 on 2023-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_transaction_approved_alter_transaction_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ticket",
            field=models.CharField(default="", max_length=255),
        ),
    ]
