# Generated by Django 4.2.5 on 2023-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_transaction_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="_books_available",
            field=models.IntegerField(default=0),
        ),
    ]
