# Generated by Django 4.2.5 on 2023-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_transaction_options_bookinstance_returned"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="date_returned",
            field=models.DateField(blank=True, null=True),
        ),
    ]
